{
 "title": "Basic Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_count{instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum by(uri) (delta(http_server_requests_seconds_sum{instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) / sum by(uri) (increase(http_server_requests_seconds_count{instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_server_requests_seconds_count{instance=\"$instance\", status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Outgoing Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(client_name, uri) (delta(http_outgoing_seconds_sum[1m])) / sum by(client_name, uri) (increase(http_outgoing_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Outgoing error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by(client_name, uri, status) (increase(http_outgoing_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(client_name, uri, status) (increase(http_outgoing_seconds_count{status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(client_name, uri, status) (increase(http_outgoing_seconds_count{status=\"CLIENT_ERROR\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "sum by(repository, method) (delta(spring_data_repository_invocations_seconds_sum[1m])) / sum by(repository, method) (increase(spring_data_repository_invocations_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{app=\"JavaObservability\"} |= ``"
    }
   ]
  },
  {
   "title": "Log errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{level=\"ERROR\"} |= ``"
    }
   ]
  }
 ]
}